<?php
session_start();
$sesnama = $_POST["txtNama"];
$sesemail = $_POST["txtEmail"];
$sespesan = $_POST["txtPesan"];
$sesnim = $_POST["nim"];
$sesnamalengkap = $_POST["namaLengkap"];
$sestempatlahir = $_POST["tempatLahir"];
$sestanggallahir = $_POST["tanggalLahir"];
$seshobi = $_POST["hobi"];
$sespasangan = $_POST["pasangan"];
$sespekerjaan = $_POST["pekerjaan"];
$sesnamaortu = $_POST["namaOrtu"];
$sesnamakakak = $_POST["namaKakak"];
$sesnamaadik = $_POST["namaAdik"];
$_SESSION["sesnama"] = $sesnama;
$_SESSION["sesemail"] = $sesemail;
$_SESSION["sespesan"] = $sespesan;
$_SESSION["sesnim"] = $sesnim;
$_SESSION["sesnamalengkap"] = $sesnamalengkap;
$_SESSION["sestempatlahir"] = $sestempatlahir;
$_SESSION["sestanggallahir"] = $sestanggallahir;
$_SESSION["seshobi"] = $seshobi;
$_SESSION["sespasangan"] = $sespasangan;
$_SESSION["sespekerjaan"] = $sespekerjaan;
$_SESSION["sesnamaortu"] = $sesnamaortu;
$_SESSION["sesnamakakak"] = $sesnamakakak;
$_SESSION["sesnamaadik"] = $sesnamaadik;
header("location: index.php");
?>